export const PartnerInfoData = [
  {
    id: 1,
    name: "Samuel Jeong",
    localTime: "Seoul +14hrs 4:20pm",
    nationality: "Korean",
    email: "sammy98@snu.ac.kr",
    univ: "Seoul National University",
    major: "German Education",
    taste: [
      { isValid: true, taste: "reading" },
      { isValid: true, taste: "for" },
      { isValid: true, taste: "fun" },
      { isValid: false, taste: "interests" },
      { isValid: false, taste: "are" },
      { isValid: true, taste: "various" },
      { isValid: true, taste: "are" },
      { isValid: false, taste: "various" },
      { isValid: true, taste: "fields" },
    ],
    meetingTimes: [],
    timesData: [
      {
        id: 1,
        main: "Tuesday 3:00 pm",
        sub: "Wednesday 5:00 am KST",
        isPartnerPick: false,
        isChecked: false,
        state: "",
        print: "",
      },
      {
        id: 2,
        main: "Tuesday 3:00 pm",
        sub: "Wednesday 5:00 am KST",
        isPartnerPick: true,
        isChecked: false,
        state: "Finalize",
        print: "Finalize",
      },
      {
        id: 3,
        main: "Tuesday 3:00 pm",
        sub: "Wednesday 5:00 am KST",
        isPartnerPick: true,
        isChecked: false,
        state: "Finalize",
        print: "Finalize",
      },
    ],
    partnerChat: [
      "hello! how are you doing?",
      "it is really nice to meet you!",
      "im looking forward to meeting you soon!!",
    ],
    myChat: [
      "im good, its nice to meet you!",
      "when would you like to meet for our first session?",
    ],
  },
];
