export const TimesData = [
  {
    id: 1,
    main: "Tuesday 3:00 pm",
    sub: "Wednesday 5:00 am KST",
    isPartnerPick: false,
    myPick: "sq",
    state: "Finalize",
  },
  {
    id: 2,
    main: "Tuesday 3:00 pm",
    sub: "Wednesday 5:00 am KST",
    isPartnerPick: true,
    myPick: "sq",
    state: "Finalize",
  },
  {
    id: 3,
    main: "Tuesday 3:00 pm",
    sub: "Wednesday 5:00 am KST",
    isPartnerPick: true,
    myPick: "sq",
    state: "Finalize",
  },
  {
    id: 4,
    main: "Tuesday 3:00 pm",
    sub: "Wednesday 5:00 am KST",
    isPartnerPick: true,
    myPick: "sq",
    state: "Finalize",
  },
  {
    id: 5,
    main: "Tuesday 3:00 pm",
    sub: "Wednesday 5:00 am KST",
    isPartnerPick: true,
    myPick: "sq",
    state: "Finalize",
  },
];
